'''
Utility functions for library, includes jax utils, activations and norm functions

Mostly generated by Gemini Pro 3
'''
import jax
import jax.numpy as jnp
import haiku as hk
from functools import partial
from jax import vmap

def jax_status():
    print("Total Devices:",jax.devices())
    print("Used Devices:",jax.local_devices())
    print("Using", jnp.ones(3).device)
    # print("Using", jnp.ones(3).device.device_kind) #v0.6.0

# required to enable hk.Initializer to be pure func and accessed as func
# see https://github.com/google-deepmind/dm-haiku/issues/24
def initializer_to_function(cls):
    def sample(shape, dtype):
        return cls(shape, dtype)
    return partial(hk.transform(sample, apply_rng=True).apply, {})

@jax.jit
def scatter(input, dim, index, src, reduce=None):
    # JAX-port of PyTorch's scatter. See https://pytorch.org/docs/stable/generated/torch.Tensor.scatter_.html
    # Writes all values from the tensor src into input at the indices specified in the index tensor.
    # For each value in src, its output index is specified by its index in src for dimension != dim and by the corresponding value in index for dimension = dim.
    # One can simplify this implementation with ndarray.at (ref: https://github.com/google/jax/issues/8487)

    dnums = jax.lax.ScatterDimensionNumbers(update_window_dims=(), inserted_window_dims=(0,), scatter_dims_to_operand_dims=(0,))

    if reduce is None:
        _scatter = jax.lax.scatter
    elif reduce == "add":
        _scatter = jax.lax.scatter_add
    elif reduce == "multiply":
        _scatter = jax.lax.scatter_mul

    _scatter = partial(_scatter, dimension_numbers=dnums)
    vmap_inner = partial(vmap, in_axes=(0, 0, 0), out_axes=0)

    for _ in range(len(input.shape)-1):
        _scatter = vmap_inner(_scatter)
    swap = lambda x: jnp.swapaxes(x, dim, -1)
    input, index, src = list(map(swap, (input, index, src)))
    return swap(_scatter(input, jnp.expand_dims(index, axis=-1), src))

@jax.jit
def min_max_normalize(x, axis=None, eps=1e-8):
    """
    Applies Min-Max normalization to a JAX array, scaling values to the [0, 1] range.

    Formula: (x - min(x)) / (max(x) - min(x) + eps)

    Args:
        x: The input JAX array.
        axis: The axis or axes along which to compute the min and max.
              If None (default), computes over the entire array.
              For example, use axis=-1 to normalize independently across the last dimension.
        eps: A small constant to prevent division by zero if all elements are equal.

    Returns:
        A JAX array of the same shape, scaled to the interval [0, 1].
    """
    # keepdims=True is crucial here so that the shapes broadcast correctly
    # when we subtract the min and divide by the range.
    x_min = jnp.min(x, axis=axis, keepdims=True)
    x_max = jnp.max(x, axis=axis, keepdims=True)

    return (x - x_min) / (x_max - x_min + eps)

# We use functools.partial to pass static_argnames to the JIT compiler.
# 'axis' must be static because it changes the shape of the intermediate
# 'norm' tensor, which JAX needs to know at compile time.
@partial(jax.jit, static_argnames=['axis'])
def normalize_l2(x: jax.Array, axis: int | tuple[int, ...] | None = -1, eps: float = 1e-12) -> jax.Array:
    """
    Normalizes a JAX array along the specified axis so it has a unit L2 norm.

    Args:
        x: The input jax.numpy array.
        axis: The axis or axes along which to compute the norm.
              If None, computes the norm of the flattened array.
              Defaults to -1 (the last axis).
        eps: A small epsilon value to prevent division by zero
             (improves numerical stability during backpropagation).

    Returns:
        The normalized array where the L2 norm along 'axis' is 1.0.
    """
    # 1. Compute the L2 norm along the specified axes.
    # We use jnp.sqrt and jnp.sum of squares manually here because jnp.linalg.norm
    # has limitations when 'axis' is a tuple with more than 2 dimensions.
    # keepdims=True is crucial here so the resulting norm tensor has the
    # same number of dimensions as 'x', allowing it to broadcast correctly.
    norm = jnp.sqrt(jnp.sum(jnp.square(x), axis=axis, keepdims=True))

    # 2. Prevent division by zero.
    # We use jnp.maximum instead of a conditional statement because it's
    # highly optimized for XLA and provides stable gradients.
    safe_norm = jnp.maximum(norm, eps)

    # 3. Scale the original tensor
    return x / safe_norm
